version: '3.4'

services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      - POSTGRES_USER=scofield
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 5432:5432
